name: build

on:
  push:
    branches:
      - "**"
    tags:
      - "v*.*.*"

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [15.x]

    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install Cosign
        uses: sigstore/cosign-installer@main
        with:
          cosign-release: "v1.0.0"
      - name: install cosign private key
        run: 'echo "$COSIGN_KEY" > cosign.key'
        shell: bash
        env:
          COSIGN_KEY: ${{secrets.COSIGN_KEY}}
      - run: sudo apt-get install -y jo
      - run: mkdir -p release/
      - run: npm install
      - run: npm run pkg:prep
      - run: npm run pkg:build
      - run: |
          echo -n "${{secrets.COSIGN_PASSWORD}}" | cosign sign-blob -key cosign.key release/sift-cli-linux > release/sift-cli-linux.sig
      - run: |
          cp cosign.pub release/sift-cli.pub
      - name: release
        if: startsWith(github.ref, 'refs/tags/')
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: release/*
          tag: ${{ github.ref }}
          overwrite: true
          file_glob: true
