name: docker

on:
  push:
    branches:
      - "**"
    tags:
      - "v*.*.*"

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [15.x]

    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - run: sudo apt-get install -y jo
      - run: mkdir -p release/
      - run: npm install
      - run: npm run pkg:prep
      - run: npm run pkg:build
      - run: npm run pkg:hash
      - uses: oplik0/openpgp-action@v1
        with:
          text: release/sift-cli-linux.sha256
          key: ${{ secrets.PGP_PUBLIC_KEY }}
          privateKey: ${{ secrets.PGP_PRIVATE_KEY }}
      - name: release
        if: startsWith(github.ref, 'refs/tags/')
        uses: svenstaro/upload-release-action@v2
        with:
          file: release/*
          tag: ${{ github.ref }}
          overwrite: true
          file_glob: true
